SQLALCHEMY_DATABASE_URI = 'mysql://localhost:3306/blog'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_POOL_RECYCLE = 1800
SECRET_KEY = 'Myblog2016'
UPLOAD_FOLDER = './uploads'
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])